language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
jobs:
  include:
    - stage: style checks
      script: cargo fmt -- --check
      script: cargo clippy -- -D warnings
