language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  jobs:
    include:
      - stage: style checks
        script: cargo fmt -- --check
        script: cargo clippy -- -D warnings
      - stage: unit tests
        script: cargo test --verbose
      - stage: build
        script: cargo build --verbose
