language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
  - cargo test
  - cargo build --release
